// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: todos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A single Todo item.
type Todo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`      // Unique identifier
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`  // Todo description
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"` // Completion status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_todos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_todos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_todos_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Todo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Todo) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

// Create
type CreateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoRequest) Reset() {
	*x = CreateTodoRequest{}
	mi := &file_todos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest) ProtoMessage() {}

func (x *CreateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoRequest.ProtoReflect.Descriptor instead.
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return file_todos_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTodoRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreateTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoResponse) Reset() {
	*x = CreateTodoResponse{}
	mi := &file_todos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoResponse) ProtoMessage() {}

func (x *CreateTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoResponse.ProtoReflect.Descriptor instead.
func (*CreateTodoResponse) Descriptor() ([]byte, []int) {
	return file_todos_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTodoResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

// Read (List)
type ListTodosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosRequest) Reset() {
	*x = ListTodosRequest{}
	mi := &file_todos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest) ProtoMessage() {}

func (x *ListTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosRequest.ProtoReflect.Descriptor instead.
func (*ListTodosRequest) Descriptor() ([]byte, []int) {
	return file_todos_proto_rawDescGZIP(), []int{3}
}

type ListTodosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todos         []*Todo                `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosResponse) Reset() {
	*x = ListTodosResponse{}
	mi := &file_todos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosResponse) ProtoMessage() {}

func (x *ListTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosResponse.ProtoReflect.Descriptor instead.
func (*ListTodosResponse) Descriptor() ([]byte, []int) {
	return file_todos_proto_rawDescGZIP(), []int{4}
}

func (x *ListTodosResponse) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

// Update
type UpdateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoRequest) Reset() {
	*x = UpdateTodoRequest{}
	mi := &file_todos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest) ProtoMessage() {}

func (x *UpdateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return file_todos_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTodoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTodoRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UpdateTodoRequest) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type UpdateTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoResponse) Reset() {
	*x = UpdateTodoResponse{}
	mi := &file_todos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoResponse) ProtoMessage() {}

func (x *UpdateTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoResponse.ProtoReflect.Descriptor instead.
func (*UpdateTodoResponse) Descriptor() ([]byte, []int) {
	return file_todos_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTodoResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

// Delete
type DeleteTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoRequest) Reset() {
	*x = DeleteTodoRequest{}
	mi := &file_todos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoRequest) ProtoMessage() {}

func (x *DeleteTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoRequest.ProtoReflect.Descriptor instead.
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return file_todos_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTodoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoResponse) Reset() {
	*x = DeleteTodoResponse{}
	mi := &file_todos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoResponse) ProtoMessage() {}

func (x *DeleteTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoResponse.ProtoReflect.Descriptor instead.
func (*DeleteTodoResponse) Descriptor() ([]byte, []int) {
	return file_todos_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTodoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Server Streaming
type StreamTodosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTodosRequest) Reset() {
	*x = StreamTodosRequest{}
	mi := &file_todos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTodosRequest) ProtoMessage() {}

func (x *StreamTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTodosRequest.ProtoReflect.Descriptor instead.
func (*StreamTodosRequest) Descriptor() ([]byte, []int) {
	return file_todos_proto_rawDescGZIP(), []int{9}
}

type StreamTodosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTodosResponse) Reset() {
	*x = StreamTodosResponse{}
	mi := &file_todos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTodosResponse) ProtoMessage() {}

func (x *StreamTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTodosResponse.ProtoReflect.Descriptor instead.
func (*StreamTodosResponse) Descriptor() ([]byte, []int) {
	return file_todos_proto_rawDescGZIP(), []int{10}
}

func (x *StreamTodosResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

// Client Streaming
type BulkCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateRequest) Reset() {
	*x = BulkCreateRequest{}
	mi := &file_todos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateRequest) ProtoMessage() {}

func (x *BulkCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateRequest.ProtoReflect.Descriptor instead.
func (*BulkCreateRequest) Descriptor() ([]byte, []int) {
	return file_todos_proto_rawDescGZIP(), []int{11}
}

func (x *BulkCreateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type BulkCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedCount  int32                  `protobuf:"varint,1,opt,name=created_count,json=createdCount,proto3" json:"created_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateResponse) Reset() {
	*x = BulkCreateResponse{}
	mi := &file_todos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateResponse) ProtoMessage() {}

func (x *BulkCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateResponse.ProtoReflect.Descriptor instead.
func (*BulkCreateResponse) Descriptor() ([]byte, []int) {
	return file_todos_proto_rawDescGZIP(), []int{12}
}

func (x *BulkCreateResponse) GetCreatedCount() int32 {
	if x != nil {
		return x.CreatedCount
	}
	return 0
}

// Bidirectional Streaming
type SyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*SyncRequest_Create
	//	*SyncRequest_Update
	//	*SyncRequest_Delete
	Action        isSyncRequest_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_todos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_todos_proto_rawDescGZIP(), []int{13}
}

func (x *SyncRequest) GetAction() isSyncRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *SyncRequest) GetCreate() *CreateTodoRequest {
	if x != nil {
		if x, ok := x.Action.(*SyncRequest_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *SyncRequest) GetUpdate() *UpdateTodoRequest {
	if x != nil {
		if x, ok := x.Action.(*SyncRequest_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *SyncRequest) GetDelete() *DeleteTodoRequest {
	if x != nil {
		if x, ok := x.Action.(*SyncRequest_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

type isSyncRequest_Action interface {
	isSyncRequest_Action()
}

type SyncRequest_Create struct {
	Create *CreateTodoRequest `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type SyncRequest_Update struct {
	Update *UpdateTodoRequest `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

type SyncRequest_Delete struct {
	Delete *DeleteTodoRequest `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

func (*SyncRequest_Create) isSyncRequest_Action() {}

func (*SyncRequest_Update) isSyncRequest_Action() {}

func (*SyncRequest_Delete) isSyncRequest_Action() {}

type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*SyncResponse_Todo
	//	*SyncResponse_Error
	Result        isSyncResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_todos_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todos_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_todos_proto_rawDescGZIP(), []int{14}
}

func (x *SyncResponse) GetResult() isSyncResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SyncResponse) GetTodo() *Todo {
	if x != nil {
		if x, ok := x.Result.(*SyncResponse_Todo); ok {
			return x.Todo
		}
	}
	return nil
}

func (x *SyncResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*SyncResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isSyncResponse_Result interface {
	isSyncResponse_Result()
}

type SyncResponse_Todo struct {
	Todo *Todo `protobuf:"bytes,1,opt,name=todo,proto3,oneof"`
}

type SyncResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*SyncResponse_Todo) isSyncResponse_Result() {}

func (*SyncResponse_Error) isSyncResponse_Result() {}

var File_todos_proto protoreflect.FileDescriptor

const file_todos_proto_rawDesc = "" +
	"\n" +
	"\vtodos.proto\">\n" +
	"\x04Todo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\"'\n" +
	"\x11CreateTodoRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"/\n" +
	"\x12CreateTodoResponse\x12\x19\n" +
	"\x04todo\x18\x01 \x01(\v2\x05.TodoR\x04todo\"\x12\n" +
	"\x10ListTodosRequest\"0\n" +
	"\x11ListTodosResponse\x12\x1b\n" +
	"\x05todos\x18\x01 \x03(\v2\x05.TodoR\x05todos\"K\n" +
	"\x11UpdateTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\"/\n" +
	"\x12UpdateTodoResponse\x12\x19\n" +
	"\x04todo\x18\x01 \x01(\v2\x05.TodoR\x04todo\"#\n" +
	"\x11DeleteTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteTodoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12StreamTodosRequest\"0\n" +
	"\x13StreamTodosResponse\x12\x19\n" +
	"\x04todo\x18\x01 \x01(\v2\x05.TodoR\x04todo\"'\n" +
	"\x11BulkCreateRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"9\n" +
	"\x12BulkCreateResponse\x12#\n" +
	"\rcreated_count\x18\x01 \x01(\x05R\fcreatedCount\"\xa1\x01\n" +
	"\vSyncRequest\x12,\n" +
	"\x06create\x18\x01 \x01(\v2\x12.CreateTodoRequestH\x00R\x06create\x12,\n" +
	"\x06update\x18\x02 \x01(\v2\x12.UpdateTodoRequestH\x00R\x06update\x12,\n" +
	"\x06delete\x18\x03 \x01(\v2\x12.DeleteTodoRequestH\x00R\x06deleteB\b\n" +
	"\x06action\"M\n" +
	"\fSyncResponse\x12\x1b\n" +
	"\x04todo\x18\x01 \x01(\v2\x05.TodoH\x00R\x04todo\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result2\x8e\x03\n" +
	"\vTodoService\x125\n" +
	"\n" +
	"CreateTodo\x12\x12.CreateTodoRequest\x1a\x13.CreateTodoResponse\x122\n" +
	"\tListTodos\x12\x11.ListTodosRequest\x1a\x12.ListTodosResponse\x125\n" +
	"\n" +
	"UpdateTodo\x12\x12.UpdateTodoRequest\x1a\x13.UpdateTodoResponse\x125\n" +
	"\n" +
	"DeleteTodo\x12\x12.DeleteTodoRequest\x1a\x13.DeleteTodoResponse\x12:\n" +
	"\vStreamTodos\x12\x13.StreamTodosRequest\x1a\x14.StreamTodosResponse0\x01\x12<\n" +
	"\x0fBulkCreateTodos\x12\x12.BulkCreateRequest\x1a\x13.BulkCreateResponse(\x01\x12,\n" +
	"\tSyncTodos\x12\f.SyncRequest\x1a\r.SyncResponse(\x010\x01B$Z\"grpc-tunnel/examples/_shared/protob\x06proto3"

var (
	file_todos_proto_rawDescOnce sync.Once
	file_todos_proto_rawDescData []byte
)

func file_todos_proto_rawDescGZIP() []byte {
	file_todos_proto_rawDescOnce.Do(func() {
		file_todos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todos_proto_rawDesc), len(file_todos_proto_rawDesc)))
	})
	return file_todos_proto_rawDescData
}

var file_todos_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_todos_proto_goTypes = []any{
	(*Todo)(nil),                // 0: Todo
	(*CreateTodoRequest)(nil),   // 1: CreateTodoRequest
	(*CreateTodoResponse)(nil),  // 2: CreateTodoResponse
	(*ListTodosRequest)(nil),    // 3: ListTodosRequest
	(*ListTodosResponse)(nil),   // 4: ListTodosResponse
	(*UpdateTodoRequest)(nil),   // 5: UpdateTodoRequest
	(*UpdateTodoResponse)(nil),  // 6: UpdateTodoResponse
	(*DeleteTodoRequest)(nil),   // 7: DeleteTodoRequest
	(*DeleteTodoResponse)(nil),  // 8: DeleteTodoResponse
	(*StreamTodosRequest)(nil),  // 9: StreamTodosRequest
	(*StreamTodosResponse)(nil), // 10: StreamTodosResponse
	(*BulkCreateRequest)(nil),   // 11: BulkCreateRequest
	(*BulkCreateResponse)(nil),  // 12: BulkCreateResponse
	(*SyncRequest)(nil),         // 13: SyncRequest
	(*SyncResponse)(nil),        // 14: SyncResponse
}
var file_todos_proto_depIdxs = []int32{
	0,  // 0: CreateTodoResponse.todo:type_name -> Todo
	0,  // 1: ListTodosResponse.todos:type_name -> Todo
	0,  // 2: UpdateTodoResponse.todo:type_name -> Todo
	0,  // 3: StreamTodosResponse.todo:type_name -> Todo
	1,  // 4: SyncRequest.create:type_name -> CreateTodoRequest
	5,  // 5: SyncRequest.update:type_name -> UpdateTodoRequest
	7,  // 6: SyncRequest.delete:type_name -> DeleteTodoRequest
	0,  // 7: SyncResponse.todo:type_name -> Todo
	1,  // 8: TodoService.CreateTodo:input_type -> CreateTodoRequest
	3,  // 9: TodoService.ListTodos:input_type -> ListTodosRequest
	5,  // 10: TodoService.UpdateTodo:input_type -> UpdateTodoRequest
	7,  // 11: TodoService.DeleteTodo:input_type -> DeleteTodoRequest
	9,  // 12: TodoService.StreamTodos:input_type -> StreamTodosRequest
	11, // 13: TodoService.BulkCreateTodos:input_type -> BulkCreateRequest
	13, // 14: TodoService.SyncTodos:input_type -> SyncRequest
	2,  // 15: TodoService.CreateTodo:output_type -> CreateTodoResponse
	4,  // 16: TodoService.ListTodos:output_type -> ListTodosResponse
	6,  // 17: TodoService.UpdateTodo:output_type -> UpdateTodoResponse
	8,  // 18: TodoService.DeleteTodo:output_type -> DeleteTodoResponse
	10, // 19: TodoService.StreamTodos:output_type -> StreamTodosResponse
	12, // 20: TodoService.BulkCreateTodos:output_type -> BulkCreateResponse
	14, // 21: TodoService.SyncTodos:output_type -> SyncResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_todos_proto_init() }
func file_todos_proto_init() {
	if File_todos_proto != nil {
		return
	}
	file_todos_proto_msgTypes[13].OneofWrappers = []any{
		(*SyncRequest_Create)(nil),
		(*SyncRequest_Update)(nil),
		(*SyncRequest_Delete)(nil),
	}
	file_todos_proto_msgTypes[14].OneofWrappers = []any{
		(*SyncResponse_Todo)(nil),
		(*SyncResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todos_proto_rawDesc), len(file_todos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todos_proto_goTypes,
		DependencyIndexes: file_todos_proto_depIdxs,
		MessageInfos:      file_todos_proto_msgTypes,
	}.Build()
	File_todos_proto = out.File
	file_todos_proto_goTypes = nil
	file_todos_proto_depIdxs = nil
}
